language: rust
rust:
- 1.24.0
before_install:
- sudo apt-get install mingw-w64
- rustup target install x86_64-pc-windows-gnu
- rustup target install i686-pc-windows-gnu
script:
- cargo build --release --target x86_64-unknown-linux-gnu
- cargo build --release --target x86_64-pc-windows-gnu
- echo 'panic = "abort"' >> Cargo.toml
- cargo build --release --target i686-pc-windows-gnu
before_deploy:
- mv target/i686-pc-windows-gnu/release/fo2dat.exe target/i686-pc-windows-gnu/release/fo2dat-i686.exe
deploy:
  provider: releases
  on:
    tags: true
  api_key:
    secure: ne04gFgMTioEQmlRb53SmPcFHim7WU9AAdIl70wneMrkA7Cgr4zfjO0QjQA903etu+9e7hxlpRS0OcBq7CiqSOh7b8H457i3YycE2r2HFhBXGMMFJvA+rw93Xul7lJZ8EjsUCa3RVEqYkk+xbJpT4luW96YaOXrPWzCNk8C/wIa/Zp0mBVuQ2/yG6oBDkgugMcw7SOHg2q/q5g0uH09C8RR5rr8IbxqL2aLfFHBnOnOjCXhylP07YYidQrvVnlEnMQG4vZRGEJSE8BQIjZ7lxSYCDksiWvvvAwVS2XOk7j2r6vB+xJtFXGXLLQdRU7HG1Zs7WzRAoFO4dYWnYo6+w9EgfmzTHPr26wCw0hcqB20KooRP1x8f1spCfxwx93NN2fR+VtXsdrdVIiWyX6uyywoKNZJSarQZrXks8+KXhK2CwnpePJNT4cRaQ9ybq8OzHmtJ5vIvEwdMarkvQJSjhbxviiVirrp3Dch/mGfUHlRovI//Mc8hoYmw5M9zLVM2ibp+ueKrFKwko1qjuWlSNkWSJv2amnObZ4xl6atxaj0OWWfsqo8K1Ep8gKTced0RQaGoV0rT+LuFzaX6UkuWIANzgIVTPrt+81nfbsluw8iopgsRz14SrhImJn+FMRhEAFp7SJZsAjc4CVcpoBPBOGtIVsRT+9zELGftmC6dIg4=
  skip_cleanup: true
  file:
  - target/x86_64-unknown-linux-gnu/release/fo2dat
  - target/x86_64-pc-windows-gnu/release/fo2dat.exe
  - target/i686-pc-windows-gnu/release/fo2dat-i686.exe
