[package]
name = "fo2dat"
version = "0.0.10"
authors = ["Adam Kewley <contact@adamkewley.com>"]

[dependencies]
memmap = "0.6.2"
byteorder = "1.2.2"
clap = "2.31.2"
flate2 = "1.0.1"
rayon = "1.0.3"

[profile.release]
lto = true
